const SCENES=["Schlafzimmer, warmes Lampenlicht","Hotelzimmer bei Nacht","Marmordusche, Dampf","Badewanne, Kerzen","Strand bei Nacht","Auto, Innenraum","Waldlichtung, Mondlicht","Club, rotes Licht","Spiegelkabine","Weißes Fotostudio"];
const VOICE_PRESETS=[{id:"warm",label:"Warm und weich",pitch:1.02,rate:0.92},{id:"hell",label:"Hell und verspielt",pitch:1.18,rate:1.02},{id:"tief",label:"Tief und intim",pitch:0.88,rate:0.86},{id:"rauchig",label:"Rauchig und ruhig",pitch:0.84,rate:0.82},{id:"fluester",label:"Flüsternd und nah",pitch:0.95,rate:0.78},{id:"klar",label:"Selbstbewusst und klar",pitch:1.05,rate:0.96}];
const MOTIONS=["langsamer Kameraschwenk, weiches Atmen, Haar bewegt sich","steht auf und kommt auf die Kamera zu","dreht sich, Blick über die Schulter","setzt sich, Hände gleiten über die Haut","geht durch den Raum, Gegenlicht"];
const PRESETS=[
{id:"lena",name:"Lena",desc:"26, lange dunkle Wellen, olivfarbene Haut, schlank, selbstbewusster Blick",scene:SCENES[0],shots:["Porträt auf der Bettkante","liegt auf dem Rücken, Blick in die Kamera","steht im Türrahmen, Nachthemd"]},
{id:"mira",name:"Mira",desc:"29, kurze blonde Haare, helle Haut, athletisch, Sommersprossen",scene:SCENES[2],shots:["unter der Dusche, Wasser auf der Haut","am Waschbecken, nasse Haare","Handtuch, Dampf im Raum"]},
{id:"nora",name:"Nora",desc:"24, rote lockige Haare, Sommersprossen, volle Lippen, natürliche Figur",scene:SCENES[3],shots:["in der Badewanne, Kerzen","nasse Haare über der Schulter","steigt aus der Wanne"]},
{id:"svea",name:"Svea",desc:"31, dunkelbraune glatte Haare, hohe Wangenknochen, elegant",scene:SCENES[1],shots:["am Hotel-Fenster, Stadtlichter","auf dem Bettrand","im Spiegel der Suite"]},
{id:"aya",name:"Aya",desc:"27, schwarzes glattes Haar, warmes Goldlicht auf der Haut, schmale Schultern",scene:SCENES[4],shots:["am nächtlichen Strand","Wellen im Hintergrund","Sand auf der Haut"]},
{id:"kim",name:"Kim",desc:"25, asiatisch, Pony, dunkle Augen, zierlich, fotorealistisch",scene:SCENES[8],shots:["vor dem Spiegel","zieht das Top aus","Blick direkt in die Linse"]},
{id:"elena",name:"Elena",desc:"33, welliges braunes Haar, volle Hüften, ruhige Ausstrahlung",scene:SCENES[6],shots:["Mondlicht auf der Lichtung","lehnt an einem Baum","geht barfuß"]},
{id:"zoe",name:"Zoe",desc:"22, pinke Highlights in schwarzem Haar, piercing, mutiger Blick",scene:SCENES[7],shots:["rotes Clublicht","an der Bar","tanzend, nah"]},
{id:"priya",name:"Priya",desc:"28, langes schwarzes Haar, braune Haut, goldener Schmuck",scene:SCENES[9],shots:["Studio, weißer Hintergrund","seitliches Porträt","sitzt auf dem Boden"]},
{id:"hannah",name:"Hannah",desc:"30, dunkelblond, Sommersprossen, kräftige Schenkel, offenes Lachen",scene:SCENES[5],shots:["auf dem Beifahrersitz","Nacht, Armaturenbrett-Licht","lehnt sich zur Kamera"]}
];
const store={load(){try{return JSON.parse(localStorage.getItem("mydream.v2")||"{}")}catch{return{}}},save(d){localStorage.setItem("mydream.v2",JSON.stringify(d))}};
const state={people:[],media:[],selected:[],length:10,voice:"warm",selfDataUrl:null,openPerson:null};
function uid(){return Math.random().toString(36).slice(2,10)}
function $(id){return document.getElementById(id)}
function imageUrl(prompt,seed){const p=encodeURIComponent(`photorealistic, cinematic 85mm, natural skin, adult woman 18+, ${prompt}`);return `https://image.pollinations.ai/prompt/${p}?width=768&height=1024&nologo=true&enhance=true&seed=${seed||Date.now()}`}
function videoTryUrl(prompt,seconds){const p=encodeURIComponent(`photorealistic cinematic video of adult woman 18+, smooth motion, ${prompt}`);const t=Math.min(Math.max(seconds||8,5),30);return `https://image.pollinations.ai/prompt/${p}?model=seedance&width=768&height=1024&nologo=true&duration=${t}`}
function persist(){store.save({people:state.people,media:state.media,selected:state.selected})}
function hydrate(){const d=store.load();const base=PRESETS.map(p=>({...p,custom:false}));if(d.people&&d.people.length){state.people=[...base,...d.people.filter(p=>p.custom)]}else state.people=base;state.media=d.media||[];state.selected=d.selected&&d.selected.length?d.selected:[state.people[0].id]}
function fillSelect(el,items,map){el.innerHTML=items.map(map).join("")}
function showView(name){document.querySelectorAll(".view").forEach(v=>v.classList.add("hidden"));$("view-"+name).classList.remove("hidden");document.querySelectorAll(".nav").forEach(b=>b.classList.toggle("on",b.dataset.view===name))}
function selectedPeople(){return state.people.filter(p=>state.selected.includes(p.id))}
function sceneValue(){return $("scene")?.value||SCENES[0]}
function setStatus(t){const s=$("status");if(s)s.textContent=t}
function composePrompt(extra){const folks=selectedPeople();const names=folks.map(p=>`${p.name}: ${p.desc}`).join(". ");const action=extra||$("action")?.value||"Porträt, Blick in die Kamera";const together=folks.length>1?`${folks.length} erwachsene Frauen in derselben Szene, interagieren.`:"eine erwachsene Frau.";const self=state.selfDataUrl?"Zweite Person aus Nutzerfoto ist in der Interaktion.":"";return `${together} ${names}. Szene: ${sceneValue()}. Handlung: ${action}. ${self}`}
function hash(str){let n=1;for(let i=0;i<str.length;i++)n=(n*31+str.charCodeAt(i))>>>0;return n}
function presetCover(p){return imageUrl(`${p.desc}. ${p.scene}. ${p.shots[0]}`,hash(p.id))}
function renderPresets(){$("preset-grid").innerHTML=PRESETS.map(p=>`<article class="card" data-open="${p.id}"><img alt="${p.name}" src="${presetCover(p)}"/><div class="cap">${p.name}<small>${p.scene}</small></div></article>`).join("")}
function openPerson(id){const p=state.people.find(x=>x.id===id)||PRESETS.find(x=>x.id===id);if(!p)return;state.openPerson=p.id;if(!state.selected.includes(p.id))state.selected=[p.id];$("person-title").textContent=p.name;$("person-desc").textContent=`${p.desc}. ${p.scene}.`;const shots=p.shots||["Porträt"];$("person-images").innerHTML=shots.map(shot=>`<article class="card"><img alt="${shot}" src="${imageUrl(`${p.desc}. ${p.scene}. ${shot}`,hash(p.id+shot))}"/><div class="cap">${shot}</div></article>`).join("");$("person-videos").innerHTML=MOTIONS.slice(0,3).map((m,i)=>`<article class="card" data-make-clip="${p.id}" data-motion="${i}"><img alt="${m}" src="${imageUrl(`${p.desc}. ${p.scene}. ${m}`,hash(p.id+"v"+i))}"/><div class="cap">Clip ${i+1} <span class="badge">Video</span><small>${m}</small></div></article>`).join("");persist();showView("person")}
function renderPeople(){const html=state.people.map(p=>`<div class="person ${state.selected.includes(p.id)?"active":""}" data-id="${p.id}"><h3>${p.name}</h3><p>${p.desc.slice(0,80)}${p.desc.length>80?"…":""}</p></div>`).join("");$("people-list").innerHTML=html;$("studio-people").innerHTML=html;$("active-chips").innerHTML=selectedPeople().map(p=>`<span class="chip">${p.name}</span>`).join("")||`<span class="chip">Keine Person</span>`}
function renderGallery(){const items=state.media.slice().reverse();$("gallery").innerHTML=items.length?items.map(m=>`<article class="card">${m.type==="video"?`<video src="${m.src}" controls playsinline></video>`:`<img alt="" src="${m.src}"/>`}<div class="cap">${m.title}<small>${m.scene||""}</small></div></article>`).join(""):`<p class="hint">Noch keine eigenen Medien.</p>`}
function addMedia(type,src,title){state.media.push({id:uid(),type,src,title,scene:sceneValue(),people:state.selected.slice(),created:Date.now()});persist();renderGallery()}
function loadImage(src){return new Promise((resolve,reject)=>{const img=new Image();img.crossOrigin="anonymous";img.onload=()=>resolve(img);img.onerror=reject;img.src=src})}
async function tryRemoteVideo(prompt,seconds){try{const res=await fetch(videoTryUrl(prompt,seconds),{redirect:"follow"});const type=res.headers.get("content-type")||"";if(res.ok&&type.includes("video")){return URL.createObjectURL(await res.blob())}}catch(_){}return null}
async function recordFromFrames(frames,seconds){const w=576,h=768;const canvas=document.createElement("canvas");canvas.width=w;canvas.height=h;const ctx=canvas.getContext("2d");const stream=canvas.captureStream(24);const mime=MediaRecorder.isTypeSupported("video/webm;codecs=vp9")?"video/webm;codecs=vp9":MediaRecorder.isTypeSupported("video/webm")?"video/webm":"";if(!mime)throw new Error("Kein Video-Recorder");const rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:2500000});const chunks=[];rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};const done=new Promise(res=>{rec.onstop=()=>res(new Blob(chunks,{type:mime}))});rec.start();const start=performance.now();const dur=seconds*1000;function draw(now){const t=Math.min((now-start)/dur,1);const pos=t*(frames.length-1);const i=Math.floor(pos);const f=pos-i;const a=frames[i];const b=frames[Math.min(i+1,frames.length-1)];ctx.fillStyle="#000";ctx.fillRect(0,0,w,h);const zoom=1+t*0.08;const dw=w*zoom,dh=h*zoom;ctx.globalAlpha=1;ctx.drawImage(a,(w-dw)/2,(h-dh)/2,dw,dh);ctx.globalAlpha=f;ctx.drawImage(b,(w-dw)/2,(h-dh)/2,dw,dh);ctx.globalAlpha=1;if(t<1)requestAnimationFrame(draw);else rec.stop()}requestAnimationFrame(draw);return URL.createObjectURL(await done)}
async function generateVideo(promptOverride,seconds){const folks=selectedPeople();if(!folks.length){setStatus("Wähle mindestens eine Person.");return}const sec=seconds||state.length;const prompt=promptOverride||composePrompt((($("action")?.value)||"")+", Bewegung, filmischer Clip");setStatus(`Video ${sec}s wird erzeugt…`);const remote=await tryRemoteVideo(prompt,sec);if(remote){addMedia("video",remote,folks.map(p=>p.name).join(" + ")+` · ${sec}s`);const v=$("preview-video");v.src=remote;v.classList.remove("hidden");v.play().catch(()=>{});setStatus("Video vom Modell geladen.");showView("studio");return}const urls=[0,1,2,3,4].map(i=>imageUrl(`${prompt}. frame ${i+1}, slight pose change`,Date.now()+i*17));const frames=[];for(const u of urls){try{frames.push(await loadImage(u));setStatus(`Frame ${frames.length}/${urls.length}…`)}catch{}}if(frames.length<2){setStatus("Zu wenige Frames. Bild gespeichert.");addMedia("image",urls[0],folks.map(p=>p.name).join(" + "));return}const src=await recordFromFrames(frames,sec);addMedia("video",src,folks.map(p=>p.name).join(" + ")+` · ${sec}s`);const v=$("preview-video");v.src=src;v.classList.remove("hidden");v.play().catch(()=>{});setStatus(`Clip ${sec}s fertig.`);showView("studio")}
function pickFemaleVoice(){const voices=speechSynthesis.getVoices();const female=/female|woman|zira|samantha|victoria|anna|petra|hedda|katja|helena|lisa|google deutsch/i;return voices.find(v=>/de/i.test(v.lang)&&female.test(v.name))||voices.find(v=>female.test(v.name))||voices.find(v=>/de/i.test(v.lang))||voices[0]}
function speak(){const text=$("speak-text").value.trim();if(!text){setStatus("Text für die Stimme fehlt.");return}const preset=VOICE_PRESETS.find(v=>v.id===state.voice)||VOICE_PRESETS[0];speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.voice=pickFemaleVoice();u.pitch=preset.pitch;u.rate=preset.rate;u.lang=(u.voice&&u.voice.lang)||"de-DE";speechSynthesis.speak(u);setStatus(`Spricht: ${preset.label}`)}
function genImage(){const folks=selectedPeople();if(!folks.length){setStatus("Wähle mindestens eine Person.");return}addMedia("image",imageUrl(composePrompt()),folks.map(p=>p.name).join(" + "));setStatus("Bild wird geladen.");showView("studio")}
function bind(){document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>showView(b.dataset.go));$("age-yes").onclick=()=>{$("age-gate").classList.add("hidden");sessionStorage.setItem("ageok","1")};if(sessionStorage.getItem("ageok"))$("age-gate").classList.add("hidden");fillSelect($("p-scene"),SCENES,s=>`<option>${s}</option>`);fillSelect($("scene"),SCENES,s=>`<option>${s}</option>`);fillSelect($("voice"),VOICE_PRESETS,v=>`<option value="${v.id}">${v.label}</option>`);$("lengths").innerHTML=[5,10,15,20,30].map(n=>`<button data-len="${n}" class="${n===state.length?"on":""}">${n}s</button>`).join("");$("lengths").onclick=e=>{const b=e.target.closest("button");if(!b)return;state.length=Number(b.dataset.len);[...$("lengths").children].forEach(x=>x.classList.toggle("on",x===b))};$("voice").onchange=e=>{state.voice=e.target.value};$("save-person").onclick=()=>{const name=$("p-name").value.trim();const desc=$("p-desc").value.trim();if(!name||!desc){alert("Name und Beschreibung nötig.");return}const person={id:uid(),name,desc,scene:$("p-scene").value,shots:["Porträt"],custom:true};state.people.push(person);state.selected=[person.id];persist();renderPeople();$("action").value="Porträt, Blick in die Kamera";$("scene").value=person.scene;genImage()};$("use-person").onclick=()=>{const p=state.people.find(x=>x.id===state.openPerson);if(!p)return;state.selected=[p.id];$("action").value="";$("scene").value=p.scene||SCENES[0];persist();renderPeople();showView("studio")};$("play-person-video").onclick=()=>{const p=state.people.find(x=>x.id===state.openPerson);if(!p)return;state.selected=[p.id];$("scene").value=p.scene||SCENES[0];generateVideo(`${p.desc}. ${p.scene}. ${MOTIONS[0]}`,state.length)};document.body.addEventListener("click",e=>{const open=e.target.closest("[data-open]");if(open){openPerson(open.dataset.open);return}const clip=e.target.closest("[data-make-clip]");if(clip){const p=state.people.find(x=>x.id===clip.dataset.makeClip);const motion=MOTIONS[Number(clip.dataset.motion)]||MOTIONS[0];state.selected=[p.id];$("scene").value=p.scene;generateVideo(`${p.desc}. ${p.scene}. ${motion}`,state.length);return}const person=e.target.closest(".person");if(person){const id=person.dataset.id;if(state.selected.includes(id))state.selected=state.selected.filter(x=>x!==id);else state.selected.push(id);persist();renderPeople()}});$("self-photo").onchange=e=>{const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{state.selfDataUrl=r.result;$("self-preview").classList.remove("hidden");$("self-preview").innerHTML=`<img alt="Dein Foto" src="${r.result}"/>`};r.readAsDataURL(file)};$("gen-image").onclick=genImage;$("gen-video").onclick=()=>generateVideo();$("speak").onclick=speak}
hydrate();bind();renderPresets();renderPeople();renderGallery();showView("home");
