const SCENES=["Büro","Salon","Türrahmen","Schlafzimmer","Bettkante","Terrasse","Spiegel","Hotel"];
const VOICES=[{id:"warm",label:"Warm",pitch:1.02,rate:0.92},{id:"hell",label:"Hell",pitch:1.18,rate:1.02},{id:"tief",label:"Tief",pitch:0.88,rate:0.86},{id:"fluester",label:"Flüstern",pitch:0.95,rate:0.78}];
const PRESETS=[
 {id:"clara",name:"Clara",age:38,scene:"Büro",desc:"38, dunkles Hochsteckhaar, Brille, weiße Bluse Knopfleiste, grauer Rock"},
 {id:"mona",name:"Mona",age:34,scene:"Salon",desc:"34, blonder Updo, beiges Ripp-Polo aufgeknöpft"},
 {id:"ruby",name:"Ruby",age:26,scene:"Wohnung",desc:"26, rote Haare, Sommersprossen, Tattoos, oliv Rippkleid Knopfleiste"},
 {id:"saskia",name:"Saskia",age:36,scene:"Salon",desc:"36, welliges Blond, schwarzes Polo-Kleid Knopfleiste"},
 {id:"nina",name:"Nina",age:27,scene:"Haustür",desc:"27, schwarze Wellen, Brille, graues Polo Knopfleiste, Lackleggings"},
 {id:"liane",name:"Liane",age:32,scene:"Haus",desc:"32, blonder Dutt, beiges Rippkleid Knopfleiste"},
 {id:"tessa",name:"Tessa",age:29,scene:"Terrasse",desc:"29, blonder Dutt, weißes Hemd Knopfleiste"},
 {id:"vera",name:"Vera",age:28,scene:"Haustür",desc:"28, dunkles Haar, Brille, navy Polo Knopfleiste, Lackleggings"},
 {id:"jule",name:"Jule",age:31,scene:"Haustür",desc:"31, blonder Dutt, weißes Knopf-Minikleid"},
 {id:"dana",name:"Dana",age:30,scene:"Tür",desc:"30, langes schwarzes Haar, Brille, navy Ripp-Polo Knopfleiste"},
 {id:"greta",name:"Greta",age:25,scene:"Terrasse",desc:"25, rote Haare, goldene Brille, Sommersprossen, Tattoos, beiges Polo-Kleid Knopfleiste"}
];
const $=id=>document.getElementById(id);
const state={people:[],media:[],selected:[],length:10,voice:"warm",createKind:"image",openId:null,chatId:null,memory:{}};
function load(){try{return JSON.parse(localStorage.getItem("md.v5")||"{}")}catch(e){return{}}}
function save(){localStorage.setItem("md.v5",JSON.stringify({people:state.people.filter(p=>p.custom),media:state.media,selected:state.selected,memory:state.memory}))}
function hydrate(){const d=load();state.people=PRESETS.map(p=>({...p,custom:false})).concat(d.people||[]);state.media=d.media||[];state.selected=d.selected&&d.selected.length?d.selected:[state.people[0].id];state.memory=d.memory||{}}
function view(name){document.querySelectorAll(".view").forEach(v=>v.classList.add("hidden"));$("view-"+name).classList.remove("hidden");document.querySelectorAll(".nav").forEach(b=>b.classList.toggle("on",b.dataset.view===name))}
function sel(){return state.people.filter(p=>state.selected.includes(p.id))}
function person(id){return state.people.find(p=>p.id===id)}
function status(t){const s=$("status");if(s)s.textContent=t}
function hash(s){let h=0;for(let i=0;i<String(s).length;i++)h=(h*31+s.charCodeAt(i))|0;return h}
function imgUrl(prompt){const p=encodeURIComponent("photorealistic adult woman 18+ tight ribbed button polo dress "+String(prompt||"").slice(0,140));return "https://image.pollinations.ai/prompt/"+p+"?width=640&height=896&nologo=true&seed="+Math.abs(hash(prompt))}
function cover(p){return imgUrl(p.name+" "+p.desc+" "+(p.scene||"")+" standing looking at camera")}
function zoom(src){if(!$("lb-img"))return;$("lb-img").src=src;$("lightbox").classList.remove("hidden")}
function renderHome(){$("preset-grid").innerHTML=PRESETS.map(p=>`<article class="card" data-open="${p.id}"><img alt="${p.name}" src="${cover(p)}" /><div class="cap">${p.name}<small>${p.scene}</small></div></article>`).join("")}
function renderPeople(){const html=state.people.map(p=>`<div class="person ${state.selected.includes(p.id)?"active":""}" data-id="${p.id}"><h3>${p.name}</h3><p>${p.desc}</p></div>`).join("");if($("people-list"))$("people-list").innerHTML=html;if($("studio-people"))$("studio-people").innerHTML=html;if($("active-chips"))$("active-chips").innerHTML=sel().map(p=>`<span class="chip">${p.name}</span>`).join("")}
function renderGallery(){const items=state.media.slice().reverse();$("gallery").innerHTML=items.length?items.map(m=>`<article class="card" data-zoom="${m.src}">${m.type==="video"?`<video src="${m.src}" controls playsinline></video>`:`<img src="${m.src}" alt="" />`}<div class="cap">${m.title}</div></article>`).join(""):"<p class='hint'>Prompt schreiben, dann Bild erzeugen.</p>"}
function openP(id){const p=person(id);if(!p)return;state.openId=id;state.selected=[id];$("person-title").textContent=p.name;$("person-desc").textContent=p.desc;const extras=state.media.filter(m=>m.people&&m.people.includes(id));const shots=[{src:cover(p),title:"Porträt"}].concat(extras.map(m=>({src:m.src,title:m.title})));$("person-images").innerHTML=shots.map(s=>`<article class="card" data-zoom="${s.src}"><img src="${s.src}" alt="" /><div class="cap">${s.title}</div></article>`).join("");save();view("person")}
function addMedia(type,src,title){state.media.push({id:Math.random().toString(36).slice(2,8),type,src,title,people:state.selected.slice(),created:Date.now()});save();renderGallery()}
function genImage(){const folks=sel();if(!folks.length){status("Person wählen.");return}const pose=($("pose")&&$("pose").value)||"";const outfit=($("outfit")&&$("outfit").value)||"button polo";const prompt=folks.map(p=>p.desc).join(", ")+" "+($("scene").value||"")+" "+pose+" "+outfit+" "+($("action").value||"looking at camera");status("Bild kommt…");const src=imgUrl(prompt);addMedia("image",src,folks.map(p=>p.name).join(" + "));status("In der Galerie. Kurz warten bis es lädt.");view("studio")}
async function genVideo(){status("Video: erst Bild.");genImage();const text=$("speak-text")&&$("speak-text").value;if($("video-audio")&&$("video-audio").checked&&text)speak()}
function speak(){const text=($("speak-text")&&$("speak-text").value||"").trim();if(!text){status("Sprechtext fehlt.");return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);const vs=speechSynthesis.getVoices();u.voice=vs.find(v=>/female|anna|petra|zira|samantha/i.test(v.name))||vs[0];const pr=VOICES.find(v=>v.id===state.voice)||VOICES[0];u.pitch=pr.pitch;u.rate=pr.rate;speechSynthesis.speak(u);status("Spricht")}
function reply(p,msg){const mem=state.memory[p.id]||(state.memory[p.id]=[]);mem.push({role:"me",text:msg});const wants=/bild|foto|zeig|pose/.test(msg.toLowerCase());mem.push({role:"her",text:wants?"Schau in die Galerie.":"Hey. Sag Pose oder Szene."});save();return {wantsPic:wants}}
function renderChat(){const p=person(state.chatId);if($("chat-with"))$("chat-with").textContent=p?("Chat mit "+p.name):"";const mem=p&&state.memory[p.id]||[];if($("chat-log"))$("chat-log").innerHTML=mem.map(m=>`<div class="bubble ${m.role==="me"?"me":"her"}">${m.text}${m.img?`<img data-zoom="${m.img}" src="${m.img}" alt="">`:""}</div>`).join("")}
function sendChat(){const p=person(state.chatId);if(!p)return;const inp=$("chat-input");const msg=inp.value.trim();if(!msg)return;inp.value="";const r=reply(p,msg);if(r.wantsPic){const src=imgUrl(p.desc+" "+msg);state.memory[p.id][state.memory[p.id].length-1].img=src;addMedia("image",src,p.name+" Chat")}renderChat()}
function bind(){if($("age-yes"))$("age-yes").onclick=()=>{$("age-gate").classList.add("hidden");sessionStorage.setItem("ageok","1")};if(sessionStorage.getItem("ageok")&&$("age-gate"))$("age-gate").classList.add("hidden");document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>view(b.dataset.view));if($("scene"))$("scene").innerHTML=SCENES.map(s=>`<option>${s}</option>`).join("");if($("pose"))$("pose").innerHTML=["Blick in die Kamera","steht in der Tür","sitzt","lehnt an der Wand","auf dem Bett","Hand in der Hüfte"].map(s=>`<option>${s}</option>`).join("");if($("outfit"))$("outfit").innerHTML=["enges Ripp-Polo Knopfleiste","weißes Knopfkleid","navy Polo Lackleggings","weiße Bluse Rock"].map(s=>`<option>${s}</option>`).join("");if($("voice"))$("voice").innerHTML=VOICES.map(v=>`<option value="${v.id}">${v.label}</option>`).join("");if($("lengths")){$("lengths").innerHTML=[5,10,15,20,30].map(n=>`<button type="button" data-len="${n}" class="${n===10?"on":""}">${n}s</button>`).join("");$("lengths").onclick=e=>{const b=e.target.closest("button");if(!b)return;state.length=+b.dataset.len;[...$("lengths").children].forEach(x=>x.classList.toggle("on",x===b))}} if($("voice"))$("voice").onchange=e=>state.voice=e.target.value; if($("create-kind"))$("create-kind").onclick=e=>{const b=e.target.closest("button");if(!b)return;state.createKind=b.dataset.kind;[...$("create-kind").querySelectorAll("button")].forEach(x=>x.classList.toggle("on",x===b));if($("create-video-opts"))$("create-video-opts").classList.toggle("hidden",state.createKind!=="video")}; if($("save-person"))$("save-person").onclick=()=>{const name=$("p-name").value.trim(),desc=$("p-desc").value.trim();if(!name||!desc){alert("Name und Beschreibung");return}const p={id:"c"+Date.now(),name,desc,custom:true,scene:SCENES[0]};state.people.push(p);state.selected=[p.id];save();renderPeople();$("action").value=desc;genImage()}; if($("use-person"))$("use-person").onclick=()=>{if(state.openId)state.selected=[state.openId];save();renderPeople();view("studio")}; if($("chat-person"))$("chat-person").onclick=()=>{state.chatId=state.openId;renderChat();view("chat")}; if($("gen-image"))$("gen-image").onclick=e=>{e.preventDefault();genImage()}; if($("gen-video"))$("gen-video").onclick=e=>{e.preventDefault();genVideo()}; if($("speak"))$("speak").onclick=speak; if($("chat-send"))$("chat-send").onclick=sendChat; if($("chat-input"))$("chat-input").onkeydown=e=>{if(e.key==="Enter")sendChat()}; if($("lb-close"))$("lb-close").onclick=()=>$("lightbox").classList.add("hidden"); document.body.addEventListener("click",e=>{const z=e.target.closest("[data-zoom]");if(z){zoom(z.dataset.zoom);return}const open=e.target.closest("[data-open]");if(open){openP(open.dataset.open);return}const card=e.target.closest(".person");if(card&&card.dataset.id){const id=card.dataset.id;state.selected=state.selected.includes(id)?state.selected.filter(x=>x!==id):state.selected.concat(id);save();renderPeople()}})}
hydrate();bind();renderHome();renderPeople();renderGallery();
